name: ci
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:

jobs:
  humble:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: humble
          package-name: mediapipe_ros2_interfaces mediapipe_ros2_node mediapipe_ros2_py

  jazzy:
    runs-on: ubuntu-24.04
    continue-on-error: true   
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          package-name: mediapipe_ros2_interfaces
